### ISSUE TITLE
Display Sign Up / Log In dialog errors inside the dialog itself

### ISSUE THREAD

**Issue by nok-ko** [nok-ko/ChessProject#13]
## Tasks
- [x] Make `fetch()`es time out after ~6 seconds without a response.
	- [ ] Show a spinner or something while the request is pending?
- [ ] In `handleSignup()` & `handleLogin()`, display errors in the `.errorMessage` span element inside of the appropriate dialog.

**Comment by nok-ko** [comment]
Okay, shelving this for now, time to work on the chess/game session code.
