### ISSUE TITLE
Set Up the Server!

### ISSUE THREAD

**Issue by nok-ko** [nok-ko/ChessProject#3]
Let's write the backend! I think that I'll use Node.js serverside, with `express` and `express-session`. And probably SQLite for the database with some connector library or another. I might try to put the whole thing into a Docker container, too… but that could get a bit complicated. Gonna keep it simple for now!

## Task List
- [x] Make a basic Express App that just serves the static content
- [x] Set up session handling with `express-session`
- [x] #9
	- [ ] Set up email authentication!
		- [ ] (Magic links?)
- [x] Use [nginx as a reverse proxy](https://trainto.me/nginx-nodejs/) for the Node.js server
- [ ] (Bonus Points) make a post-push hook that deploys to [chess.nokko.me](http://chess.nokko.me)

**Comment by nok-ko** [comment]
Now live at https://chess.nokko.me!

**Comment by nok-ko** [comment]
#4 Completes part 1 of the backend adventure, on to SQLite and session handling next.
