### ISSUE TITLE
Basic Layout

### ISSUE THREAD

**Issue by nok-ko** [nok-ko/ChessProject#5]
We should make sure the basic structure of our app makes sense:
## Task List
- [ ] Figure out which UI elements we should include
- [ ] Make a mobile-friendly alternate layout
- [ ] Decide on a simple colour scheme and font
- [ ] Make sure our CSS follows industry practices (rem vs. em, custom properties where appropriate, etc.)
- [ ] Make a (placeholder) favicon
