### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by nok-ko** [nok-ko/ChessProject#9]
### Tasks: (Server-side)
- [x] Hash user passwords.
	- Done using the `bcrypt` module.
- [ ] On login:
	- [x] Accept an email/password pair as query parameters on the `/login` endpoint…
		- [ ] #11
	- [x] Check if a user with this email exists…
		- [x] If user does not exist, send back an error.
	- [x] Check if the password hashes alike to the hash we have stored for that user…
		- [x] If hashes don't match, send back an error.
	- [x] Generate a session token and log the user in if the hashes match.
		- [x] Send back a success message with the token and some user info on successful login.
	- [ ] Use exponential timeouts for failing login attempts. (Not allowed to do another one for 1 second, 1 second, 1 second, 10 seconds, 100 seconds…)
	- [ ] **Also implement other bot/spam prevention measures on this endpoint!**
- [ ] On signup:
	- [X] Accept K/V pairs of `{email:"…", pass:"…", handle:"…"}` as query parameters on the `/signup` endpoint:
		- [x] #10
	- [ ] **Implement bot/spam prevention measures on this endpoint!**

### Tasks: (Client-side)
- [ ] Keep track of “logged in” state
	- [x] #12
	- [ ] Display logged-in users' usernames
- [ ] #13
	- [ ] Add more form validation (Research the best way to do this!)

**Comment by nok-ko** [comment]
Currently good enough, closing for now.
